import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowRight, BookOpen, BriefcaseBusiness, CircleAlert, Code2, Database, GitBranch, GraduationCap, Layers3, Loader2, Network, Search, Sparkles, Target, Users, X } from 'lucide-react';
import { api } from '@/api';
import type { Course, Job, Project, RelatedJob, Skill, SkillGapResult, Technology, ConnectionGraph } from '@/types';

const colors: Record<string, string> = { Job: 'node-job', Skill: 'node-skill', Technology: 'node-tech', Course: 'node-course', Project: 'node-project' };
const accents: Record<string, string> = { Job: '#f59e0b', Skill: '#22c55e', Technology: '#38bdf8', Course: '#a78bfa', Project: '#fb7185' };

function App() {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [activeJob, setActiveJob] = useState('Frontend Developer');
  const [tab, setTab] = useState<'explore' | 'gap' | 'connections'>('explore');
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState('');

  useEffect(() => { api.jobs().then(data => { setJobs(data); if (data[0]) setActiveJob(data[0].title); }).catch(err => setLoadError(err.message)).finally(() => setLoading(false)); }, []);

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="brand"><div className="brand-mark"><Network size={20} /></div><span>Career<span className="brand-accent">Graph</span></span></div>
        <div className="topbar-meta"><span className="live-dot" /> CognoDB connected <span className="topbar-divider" /> <span className="mono">v1.0 / graph explorer</span></div>
      </header>
      <main>
        <section className="hero">
          <div className="eyebrow"><Sparkles size={14} /> Career intelligence, mapped</div>
          <h1>Navigate your next<br /><em>career move.</em></h1>
          <p className="hero-copy">Explore the skills, tools, courses, and projects that connect every role in the modern technology landscape.</p>
          <div className="hero-stats"><span><strong>{jobs.length || '—'}</strong> roles mapped</span><span><strong>25</strong> skills indexed</span><span><strong>8</strong> relationship types</span></div>
        </section>

        <section className="workspace">
          <aside className="sidebar">
            <div className="side-label">Select a role</div>
            <div className="job-search"><Search size={16} /><input placeholder="Search roles..." onChange={e => { const value = e.target.value; setJobs(prev => prev.filter(j => j.title.toLowerCase().includes(value.toLowerCase()) || j.category.toLowerCase().includes(value.toLowerCase()))); }} /></div>
            <div className="job-list">{jobs.map(job => <button key={job.title} className={`job-item ${activeJob === job.title ? 'selected' : ''}`} onClick={() => { setActiveJob(job.title); setTab('explore'); }}><span className="job-icon"><BriefcaseBusiness size={16} /></span><span><b>{job.title}</b><small>{job.category}</small></span>{activeJob === job.title && <ArrowRight size={15} className="job-arrow" />}</button>)}</div>
            {jobs.length === 0 && !loading && <div className="empty-small">No roles found.</div>}
            <div className="side-footer"><div className="side-footer-icon"><Database size={15} /></div><div><b>Powered by CognoDB</b><span>Connected graph database</span></div></div>
          </aside>
          <section className="content">
            {loadError ? <ErrorState message={loadError} /> : loading ? <LoadingState /> : <><nav className="tabs"><button className={tab === 'explore' ? 'active' : ''} onClick={() => setTab('explore')}><Target size={16} /> Role overview</button><button className={tab === 'gap' ? 'active' : ''} onClick={() => setTab('gap')}><Activity size={16} /> Skill gap</button><button className={tab === 'connections' ? 'active' : ''} onClick={() => setTab('connections')}><GitBranch size={16} /> Connections</button></nav>{tab === 'explore' && <RoleOverview jobTitle={activeJob} onSelectRole={setActiveJob} />}{tab === 'gap' && <SkillGap jobTitle={activeJob} />}{tab === 'connections' && <Connections jobTitle={activeJob} />}</>}
          </section>
        </section>
      </main>
      <footer className="footer"><span>CAREERGRAPH <span className="muted">/ graph database take-home</span></span><span className="footer-right"><Code2 size={14} /> Built for connected thinking</span></footer>
    </div>
  );
}

function LoadingState() { return <div className="state"><Loader2 className="spin" size={30} /><b>Connecting to the graph...</b><span>Loading career relationships from CognoDB</span></div>; }
function ErrorState({ message }: { message: string }) { return <div className="state error"><CircleAlert size={30} /><b>Graph connection unavailable</b><span>{message}</span><small>Start CognoDB and the FastAPI service, then refresh.</small></div>; }

function RoleOverview({ jobTitle, onSelectRole }: { jobTitle: string; onSelectRole: (title: string) => void }) {
  const [job, setJob] = useState<Job | null>(null); const [skills, setSkills] = useState<Skill[]>([]); const [techs, setTechs] = useState<Technology[]>([]); const [courses, setCourses] = useState<Course[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [related, setRelated] = useState<RelatedJob[]>([]); const [error, setError] = useState('');
  useEffect(() => { setError(''); Promise.all([api.job(jobTitle), api.skills(jobTitle), api.technologies(jobTitle), api.courses(jobTitle), api.projects(jobTitle), api.related(jobTitle)]).then(([j, s, t, c, p, r]) => { setJob(j); setSkills(s); setTechs(t); setCourses(c); setProjects(p); setRelated(r); }).catch(err => setError(err.message)); }, [jobTitle]);
  if (error) return <ErrorState message={error} />; if (!job) return <LoadingState />;
  return <div className="role-page"><div className="role-heading"><div><div className="breadcrumb">EXPLORE <span>/</span> {job.category.toUpperCase()}</div><h2>{job.title}</h2><p>{job.description}</p></div><div className="salary"><span>AVG. US SALARY</span><b>${Math.round(job.avg_salary / 1000)}k</b><small>per year</small></div></div>
    <div className="section-title"><span>01</span> Core requirements <small>What this role asks for</small></div><div className="skill-grid">{skills.map((s, i) => <div className="skill-card" key={s.name}><div className="card-top"><span className="index">0{i + 1}</span><span className="pill green">{s.category}</span></div><h3>{s.name}</h3><p>{s.description}</p><div className="card-line" /></div>)}</div>
    <div className="split-title"><div className="section-title"><span>02</span> Technology stack <small>Skills → tools, traversed</small></div><div className="tech-count">{techs.length} technologies</div></div><div className="tech-strip">{techs.map(t => <div className="tech-chip" key={t.name}><span className="tech-dot" />{t.name}<small>{t.category}</small></div>)}</div>
    <div className="two-col"><ResourcePanel icon={<BookOpen size={17} />} title="Courses to get there" subtitle="Skill → Course" items={courses.map(c => ({ title: c.title, meta: `${c.provider} · ${c.hours}h`, tag: c.level, url: c.url }))} type="course" /><ResourcePanel icon={<Layers3 size={17} />} title="Projects that prove it" subtitle="Skill ← Project" items={projects.map(p => ({ title: p.title, meta: p.description, tag: p.difficulty }))} type="project" /></div>
    <div className="section-title related-title"><span>03</span> Nearby career paths <small>Jobs connected by shared skills</small></div><div className="related-row">{related.map(r => <button className="related-card" key={r.title} onClick={() => onSelectRole(r.title)}><div className="related-icon"><Users size={17} /></div><div><b>{r.title}</b><span>{r.shared_skills.length ? `${r.shared_skills.length} shared skills` : r.relation}</span></div><ArrowRight size={15} /></button>)}</div>
  </div>;
}

function ResourcePanel({ icon, title, subtitle, items, type }: { icon: React.ReactNode; title: string; subtitle: string; items: { title: string; meta: string; tag: string; url?: string }[]; type: string }) { return <div className="resource-panel"><div className="panel-header"><span className={`panel-icon ${type}`}>{icon}</span><div><h3>{title}</h3><span>{subtitle}</span></div><span className="panel-count">{items.length}</span></div><div className="resource-list">{items.slice(0, 5).map(item => <a className="resource-item" key={item.title} href={item.url} target={item.url ? '_blank' : undefined} rel="noreferrer"><div><b>{item.title}</b><span>{item.meta}</span></div><span className={`pill ${type === 'course' ? 'violet' : 'rose'}`}>{item.tag}</span></a>)}</div></div>; }

function SkillGap({ jobTitle }: { jobTitle: string }) { const [allSkills, setAllSkills] = useState<Skill[]>([]); const [have, setHave] = useState<string[]>([]); const [result, setResult] = useState<SkillGapResult | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); useEffect(() => { api.allSkills().then(setAllSkills).catch(err => setError(err.message)); setResult(null); }, [jobTitle]); const toggle = (name: string) => setHave(prev => prev.includes(name) ? prev.filter(s => s !== name) : [...prev, name]); const analyze = () => { setBusy(true); setError(''); api.gap(jobTitle, have).then(setResult).catch(err => setError(err.message)).finally(() => setBusy(false)); }; return <div className="gap-page"><div className="page-intro"><div className="eyebrow"><Activity size={14} /> Personal readiness</div><h2>Close your skill gap.</h2><p>Tell us what you already know. We’ll trace the shortest path to <strong>{jobTitle}</strong>.</p></div><div className="gap-layout"><div className="skill-picker"><div className="picker-heading"><h3>Your current skills</h3><span>{have.length} selected</span></div><p className="hint">Select everything you feel comfortable using today.</p><div className="picker-grid">{allSkills.map(skill => <button key={skill.name} className={`picker-skill ${have.includes(skill.name) ? 'chosen' : ''}`} onClick={() => toggle(skill.name)}>{have.includes(skill.name) && <span className="check">✓</span>}{skill.name}</button>)}</div><button className="primary-btn" onClick={analyze} disabled={busy}>{busy ? <Loader2 className="spin" size={16} /> : <Sparkles size={16} />} Analyze my gap <ArrowRight size={16} /></button>{error && <div className="inline-error"><CircleAlert size={15} />{error}</div>}</div>{result ? <GapResult result={result} /> : <div className="gap-empty"><Target size={28} /><b>Your personalized map awaits</b><span>Choose your skills and run the analysis to see your readiness score, learning path, and project recommendations.</span></div>}</div></div>; }
function GapResult({ result }: { result: SkillGapResult }) { return <div className="gap-result"><div className="score-card"><div className="score-ring" style={{ '--score': `${result.coverage_pct * 3.6}deg` } as React.CSSProperties}><div><b>{result.coverage_pct}%</b><span>ready</span></div></div><div><span className="eyebrow">READINESS FOR {result.target_job.toUpperCase()}</span><h3>{result.coverage_pct >= 70 ? 'You’re close.' : 'Strong start.'}</h3><p>{result.matching_skills.length} of {result.matching_skills.length + result.missing_skills.length} required skills covered.</p></div></div><div className="gap-section"><div className="gap-section-head"><h3><span className="dot red" /> Skills to build</h3><span>{result.missing_skills.length} missing</span></div><div className="missing-list">{result.missing_skills.map(s => <span key={s}>{s}<X size={12} /></span>)}</div></div><div className="gap-section"><div className="gap-section-head"><h3><span className="dot green-dot" /> Skills you have</h3><span>{result.matching_skills.length} matched</span></div><div className="missing-list matched">{result.matching_skills.map(s => <span key={s}>{s}</span>)}</div></div>{result.recommended_courses.length > 0 && <div className="mini-recommend"><BookOpen size={16} /><div><b>Start with {result.recommended_courses[0].title}</b><span>{result.recommended_courses[0].provider} · {result.recommended_courses[0].hours} hours</span></div></div>}</div>; }

function Connections({ jobTitle }: { jobTitle: string }) { const [graph, setGraph] = useState<ConnectionGraph | null>(null); const [error, setError] = useState(''); useEffect(() => { setGraph(null); api.connections(jobTitle).then(setGraph).catch(err => setError(err.message)); }, [jobTitle]); const grouped = useMemo(() => graph ? graph.nodes.reduce<Record<string, typeof graph.nodes>>((acc, node) => { (acc[node.type] ||= []).push(node); return acc; }, {}) : {}, [graph]); if (error) return <ErrorState message={error} />; if (!graph) return <LoadingState />; return <div className="connections-page"><div className="page-intro"><div className="eyebrow"><GitBranch size={14} /> Relationship explorer</div><h2>See the whole picture.</h2><p>Every node around <strong>{jobTitle}</strong>, connected through real graph relationships.</p></div><div className="graph-summary"><div className="graph-canvas"><div className="grid-bg" /><div className="graph-center"><BriefcaseBusiness size={22} /><span>{jobTitle}</span></div>{Object.entries(grouped).filter(([type]) => type !== 'Job').slice(0, 5).map(([type, nodes], groupIndex) => nodes.slice(0, groupIndex === 0 ? 6 : 4).map((node, i) => { const angle = ((i - (Math.min(nodes.length, groupIndex === 0 ? 6 : 4) - 1) / 2) * 35) + (groupIndex * 72); return <div className={`graph-node ${colors[type]}`} style={{ '--angle': `${angle}deg`, '--radius': `${100 + groupIndex * 42}px` } as React.CSSProperties} key={node.id}><span className="node-line" /><span className="node-circle" style={{ background: accents[type] }}>{type === 'Skill' ? <Target size={13} /> : type === 'Technology' ? <Code2 size={13} /> : type === 'Course' ? <GraduationCap size={13} /> : <Layers3 size={13} />}</span><b>{node.label}</b></div>; }))}<div className="graph-legend">{Object.entries(accents).map(([name, color]) => <span key={name}><i style={{ background: color }} />{name}</span>)}</div></div><div className="connection-stats"><div className="connection-stat"><b>{graph.nodes.length}</b><span>nodes in view</span></div><div className="connection-stat"><b>{graph.edges.length}</b><span>relationships</span></div><div className="connection-keys">{Object.entries(grouped).map(([type, nodes]) => <div key={type}><span className="key-dot" style={{ background: accents[type] }} /><b>{nodes.length}</b> {type.toLowerCase()} nodes</div>)}</div></div></div><div className="edge-list"><div className="section-title"><span>PATHS</span> Active relationships <small>Traversed from {jobTitle}</small></div>{graph.edges.slice(0, 10).map((edge, i) => <div className="edge-row" key={`${edge.source}-${edge.target}-${i}`}><span className="edge-node">{edge.source.split(':')[1]}</span><ArrowRight size={14} /><span className="edge-type">{edge.type}</span><ArrowRight size={14} /><span className="edge-node">{edge.target.split(':')[1]}</span></div>)}</div></div>; }

export default App;
